-- fc26_mcp apply_transfers.lua -- NATIVE transfers (cTransferPlayer/cLoanPlayer)
-- Generated by fc26-mcp. Run: Live Editor -> Lua Engine -> Run.
local LOG_PATH = "C:/fc26-mcp/mcp_transfer_log.txt"
local NL = string.char(10)
local function log(msg)
    local f = io.open(LOG_PATH, "a")
    if f then f:write(os.date("%Y-%m-%d %H:%M:%S") .. " " .. msg .. NL) f:close() end
end

local T = {
    { n = "van Duinen", pid = 205603, tid = 243, wage = 5500, months = 36 },
    { n = "Bruno Iribarne", pid = 278405, tid = 1, wage = 120000, months = 48 },
}

function main()
    log("== NATIVE TRANSFERS START (2) ==")
    for _, e in ipairs(T) do
        local pid, tid = e.pid, e.tid
        local ok0, cur = pcall(GetTeamIdFromPlayerId, pid)
        if ok0 and cur == tid then
            log(e.n .. " pid=" .. pid .. " already at " .. tid .. ", skip")
        else
            local okp, p2 = pcall(IsPlayerPresigned, pid)
            if okp and p2 then pcall(DeletePresignedContract, pid) end
            local okl, l2 = pcall(IsPlayerLoanedOut, pid)
            if okl and l2 then pcall(TerminateLoan, pid) end
            local from = (ok0 and cur and cur > 0) and cur or 0
            local ok = pcall(cTransferPlayer, pid, from, tid, 0, -1, e.wage, e.months)
            local ok2, cur2 = pcall(GetTeamIdFromPlayerId, pid)
            local tn = ""
            if ok2 and cur2 and cur2 > 0 then local o3, n3 = pcall(GetTeamName, cur2) tn = tostring(n3 or "") end
            local res = (ok2 and cur2 == tid) and "OK" or "FAIL"
            log(e.n .. " pid=" .. pid .. " -> " .. tid .. " [" .. res .. "] after=" .. tostring(cur2) .. " " .. tn .. " pcall=" .. tostring(ok))
        end
    end
    log("== NATIVE TRANSFERS DONE ==")
end

main()
